import { FC, PropsWithChildren } from 'react'
import Head from 'next/head'
import Navbar from '@components/shared/navbar'

const DefaultLayout: FC<PropsWithChildren<{}>> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Joshub</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Navbar/>

      <main className="bg-landing bg-top bg-no-repeat lg:overflow-x-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="pt-10 sm:pt-16 lg:pt-0 lg:pb-14">
            <div className="mt-8">
              {children}
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default DefaultLayout
